### ISSUE TITLE
Contribute to participate in HacktoberFest 2020

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#1]
Feel free to add everything you want from blogs to codes to even show off your projects!
<br/> Happy Coding!!!
<br/>
Don't forget to star the repository and follow the author.
<br/>

**Comment by neelansh15** [comment]
Can I add a folder for Javascript?

**Comment by sujata13** [comment]
Yes Sure. Happy Coding!!!

**Comment by arm210402** [comment]
can i add a typing speed test code in python

**Comment by sujata13** [comment]
Great!!!

**Comment by kambojshalabh35** [comment]
can i add a django folder

**Comment by kambojshalabh35** [comment]
#[mkart.zip](https://github.com/sujata13/HacktoberFest-2020/files/5313234/mkart.zip)

**Comment by nikhilSolomon** [comment]
mam u havent yet reviewed my pr
