### ISSUE TITLE
Finding GCD of 2 numbers

### ISSUE THREAD

**Issue by viren-vii** [sujata13/HacktoberFest-2020#12]
Find GCD of 2 input numbers
In mathematics, the greatest common divisor of two or more integers, which are not all zero, is the largest positive integer that divides each of the integers.
E.G.
GCD of 20 and 28 is 4.
Take input 20 and 28 and output should be 4.

**Comment by viren-vii** [comment]
Assign this to me!

**Comment by Ritacheta** [comment]
Assign me please

**Comment by viren-vii** [comment]
Done
