### ISSUE TITLE
[Create] NavBar

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#185]
Create a navbar similar to the one below:<br/>
![nav-bar](https://user-images.githubusercontent.com/36507578/94906225-ba8b0300-04bb-11eb-83be-2de43ff3b8e4.png)

<h2>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING</h2>

**Comment by sujata13** [comment]
To Discuss about the HacktoberFest2020 join -
[Telegram Group] (https://t.me/hacktober_fest_2020)

**Comment by TeerapatMan** [comment]
I can do it.

**Comment by sujata13** [comment]
Sure. Go ahead. Happy Coding!!! You can also join our [Telegram group](https://t.me/hacktober_fest_2020) for having discussion.

**Comment by TeerapatMan** [comment]
Now, I joined Telegram group.
