### ISSUE TITLE
[CREATE] - Header

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#186]
Create a header section similar to the image below:

[
![header](https://user-images.githubusercontent.com/36507578/94906505-371de180-04bc-11eb-8660-7eca11b55400.png)
](url)

<h2>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING</h2>

**Comment by sujata13** [comment]
To Discuss about the HacktoberFest2020 join -
[Telegram Group] (https://t.me/hacktober_fest_2020)

**Comment by grvsood** [comment]
lemme grab this one
