### ISSUE TITLE
[CREATE] - Meet The Team

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#188]
Create the meet the team section as detailed in the image below:

![Meet the team](https://user-images.githubusercontent.com/36507578/94906875-de9b1400-04bc-11eb-8274-177be25e90bf.png)

<h2>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING</h2>

**Comment by sujata13** [comment]
To Discuss about the HacktoberFest2020 join -
[Telegram Group] (https://t.me/hacktober_fest_2020)

**Comment by grvsood** [comment]
lemme grab this

**Comment by manasi44** [comment]
can I contribute in this?

**Comment by MeerHamza1421** [comment]
can i contribute?????
