### ISSUE TITLE
[CREATE] Contact Us

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#189]
Create the contact us section as detailed below.
This is a pretty big task, so don't worry to much about getting it perfect. These are things other people can pick up to gain experience.

![Contact us](https://user-images.githubusercontent.com/36507578/94906989-13a76680-04bd-11eb-93cb-0854ac2635a1.png)

<h2>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING</h2>

**Comment by sujata13** [comment]
To Discuss about the HacktoberFest2020 join -
[Telegram Group] (https://t.me/hacktober_fest_2020)

**Comment by saiharsha-22** [comment]
@sujata13 can I work on this,  I will try to create. can you assign this task to me?

**Comment by dhavalmaniyar** [comment]
@sujata13  can i work on that?

**Comment by sujata13** [comment]
@dhavalmaniyar @saiharsha-22 Yes you can work. And can also discuss about it on our [Telegram Channel](https://t.me/hacktober_fest_2020)

Happy Coding!!!

**Comment by saiharsha-22** [comment]
@sujata13 Thank you.

**Comment by dhavalmaniyar** [comment]
@sujata13 Thank you.

**Comment by praew1202** [comment]
can i new create contact us form?

**Comment by sujata13** [comment]
Sure

**Comment by charchithere** [comment]
hello! can i work on this? pls assign it to me
