### ISSUE TITLE
[CREATE] Blog Page

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#190]
Create a blog page with similar design to:
Dont worry about the Navbar, Hero Image or Email bar, we can use these from the other tasks.

![blog page](https://user-images.githubusercontent.com/36507578/94907116-494c4f80-04bd-11eb-91da-339cfe951535.png)

<h2>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING</h2>
To Discuss about the HacktoberFest2020 join -<br/>
[Telegram Group](https://t.me/hacktober_fest_2020)

**Comment by sujata13** [comment]
To Discuss about the HacktoberFest2020 join -
[Telegram Group] (https://t.me/hacktober_fest_2020)

**Comment by prachi0513** [comment]
can I make a blog page for this to resolve this issue ?

**Comment by sujata13** [comment]
Sure. Go ahead. Happy Coding!!! You can also join our [Telegram group](https://t.me/hacktober_fest_2020) for having discussion.

**Comment by prachi0513** [comment]
okie thanks

**Comment by charchithere** [comment]
Hello! I want to work on this
