### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#2]
Write algorithms in whichever language you want either in algorithm folder or in language specific folder. <br/>
File Name format- [Your UserName]_filename
 <br/>
<b>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING<b>

**Comment by ShamikG17** [comment]
Can I work on this?

**Comment by Rj-coder-iitian** [comment]
I am having many algorithms in C language.

**Comment by akshaydesai26** [comment]
I'd like to add largest sum of contiguous subarray problem in CPP.

**Comment by sujata13** [comment]
Everyone can participate just take care of your File Name. It should have to be in the specified format.
Happy Coding!!!

**Comment by HIMANSHU3107** [comment]
I'd like to work on it, can u assign it to me!

**Comment by MihirBani2000** [comment]
I want to add Kruskal's algo in C++

**Comment by sujata13** [comment]
You can work on it.

**Comment by abhay313** [comment]
I want to add sorting and searching algorithms.

**Comment by sujata13** [comment]
Please go ahead and contribute as much as you can. 
Happy Coding!!!

**Comment by kaushambisharma** [comment]
I would love to contribute.

**Comment by Harshitbhatt69** [comment]
Added LIVE IPL scorecard in python 3, kindly merge.

**Comment by Renu-code** [comment]
i want to add djikstra algorithm.can i add?

**Comment by Renu-code** [comment]
submitted the pull request for djikstra algorithm #148 ...please review it

**Comment by rtvksingh** [comment]
i have added solution for 0-1 knapsack problem
