### ISSUE TITLE
Do's and Dont's of Hacktoberfest

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#246]
# Do's and Dont's of Hacktoberfest
<h4>Don't: open pull requests with minor text edits on other people's repositories</h4>
 If you're looking for a faster way to open four PR's and win, there's a better way!

<h4>Do: Follow a repository's contribution guidelines</h4>
 Almost every repo looking for help has a CONTRIBUTING.md file in it, read it first!

<h4>Don't: feel intimidated</h4>
 Register for an event and learn with a group, or connect with others in the [Telegram Group](https://t.me/hacktober_fest_2020)  Discord chat.

**Comment by sumitt1080** [comment]
What i have to do in this?

**Comment by sujata13** [comment]
You can contribute in other issues keeping these points in mind as there are lots of spam activities going on so this is issued by the DigitalOcean(HacktoberFest 2020).

**Comment by sumitt1080** [comment]
Can i work on your Profile readme file?

**Comment by pawank0411** [comment]
Please Add "**hacktoberfest**" topic to your repo.
Reference: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by sujata13** [comment]
@pawank0411 Thanks for informing. I have updated it.

**Comment by sujata13** [comment]
@sumitt1080  Are you talking about Readme file of this repo or 'my profile' repo?

**Comment by sumitt1080** [comment]
@sujata13 In your 'My profile' repo.

**Comment by sujata13** [comment]
Ok. you can work

**Comment by sumitt1080** [comment]
Thanks
