### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#25]
Add your website projects created using HTML, CSS and JS in the new subfolder to showcase to everyone.<br/>Happy Coding!!!

**Comment by Badkul77** [comment]
Please Assign it to me , i have a unique website ,usefull for all

**Comment by shubhavee** [comment]
I've opened a PR for adding my web dev project(using HTML, CSS, Javascript) in the Websites folder!

**Comment by sujata13** [comment]
PRs will be merged within 48 hr after reviewing it. Happy Coding!!!

**Comment by ayushi-1408** [comment]
Hey! I would love to do work on it

**Comment by sneha-nitdgp** [comment]
Hey! I added a website, an image gallery made using HTML, CSS and Javascript

**Comment by sneha-nitdgp** [comment]
Added a Quiz app made using HTML and Javascript.

**Comment by sujata13** [comment]
Feel free to contribute as much as possible.

**Comment by zahinekbal** [comment]
@sujata13 Can I add Portfolio website using HTML , Css  and JavaScript...
