### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#3]
Write data structure related programs in whichever language you want either in data structure folder or in language specific folder. <br/>
File Name format- [Your UserName]_filename
 <br/>
<b>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING<b>

**Comment by jineshparakh** [comment]
Can you please assign it to me!

**Comment by akshaydesai26** [comment]
I'd like to add largest sum of contiguous subarray problem in CPP.

**Comment by shivajipotnuru** [comment]
Hey !!! assign it to me I want to work on it :)

**Comment by HIMANSHU3107** [comment]
I'd like to work on it, can u assign it to me!

**Comment by abhay313** [comment]
I'd like to work on it, please assign it to me

**Comment by Hiteshgoyal1711** [comment]
I want to work on this pls assign it to me

**Comment by ayushi-1408** [comment]
Hey! I would love to work on this issue using c language

**Comment by kaushambisharma** [comment]
I would love to contribute.

**Comment by sneha-nitdgp** [comment]
I'd love to contribut. Please assign to me!

**Comment by CHANDRAMANI70** [comment]
can u plzz assign me??
