### ISSUE TITLE
C Programs

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#4]
Write C Programs in language specific folder. <br/>
File Name format- [Your UserName]_filename
 <br/>
<b>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING<b>

**Comment by Rj-coder-iitian** [comment]
I am up for programs in C language.

**Comment by sujata13** [comment]
Ok. Happy Coding!!!

**Comment by HIMANSHU3107** [comment]
I'd like to work on it, can u assign it to me!

**Comment by Abantika20** [comment]
I wish to work on it. Please assign it to me.

**Comment by damascus8** [comment]
Hello I also want to work on this.

**Comment by Ritacheta** [comment]
Can you please assign me?
