### ISSUE TITLE
python program for binary search

### ISSUE THREAD

**Issue by tanmaynagpal** [sujata13/HacktoberFest-2020#53]

**Comment by tanmaynagpal** [comment]
please assign this to me

**Comment by SuryaSekhar14** [comment]
Assign this to me, please!

**Comment by ruchijain4** [comment]
I would love to work on this

**Comment by Ritacheta** [comment]
Please assign me

**Comment by SuryaSekhar14** [comment]
I committed the Binary Search using Python file, under the Python Folder, please merge my Pull request.
