### ISSUE TITLE
Java Programs

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#6]
Write Java Programs in language specific folder. <br/>
File Name format- [Your UserName]_filename
 <br/>
<b>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING<b>

**Comment by pockii** [comment]
Hello, I'm interested in working on this issue. Is there a particular algorithm I should work on, or is it my choice?

**Comment by sujata13** [comment]
You can choose algorithms by yourself. Happy Coding!!!

**Comment by saiharsha-22** [comment]
@sujata13  Hello I am new to open source contribution, I would like to contribute a quick sort program in java, can I?

**Comment by saiharsha-22** [comment]
@sujata13 I have added a pull request for java quick sort, can you please check.
![Screenshot (389)](https://user-images.githubusercontent.com/61947484/94784664-2140eb80-03ec-11eb-82cd-87fc6d8f0146.png)

**Comment by Dheeraj-01** [comment]
I am adding some Famous Algorithms in java. 
Do I add it??

**Comment by sujata13** [comment]
@Dheeraj-01  Yes

**Comment by sujata13** [comment]
@saiharsha-22  It take some time to review all the Pull Request and merge them. All PR will be merged within 48 hr.

**Comment by Dheeraj-01** [comment]
ok Thanks✔

**Comment by NyorJa** [comment]
I would like to participate on this also

**Comment by Kara3** [comment]
Hi, can I also add an Algorithm in Java?

**Comment by Ayomal98** [comment]
Can i work on a java calculator

**Comment by abhay313** [comment]
I want to add few algorithms, can I proceed ?.

**Comment by DevanshiJain** [comment]
Hey, can I work on finding the height of a binary tree?

**Comment by sujata13** [comment]
Yes!!! Please go ahead and contribute as much as you can. 
Happy Coding!!!

**Comment by Raghuram07** [comment]
i can do all searching and sorting algorithms in java with the explanation and time complexities. 10-15 programs files, explanation files and a readMe file. Can i work on them..?

**Comment by NamanKansal230505** [comment]
Hey I can add all the java basic code  may i ?

**Comment by Sneha8857** [comment]
Can i add a java program?

**Comment by Achsion** [comment]
I would like to add merge sort written in java ^^

**Comment by ishanbagchi** [comment]
@sujata13 if I add a program like a calculator or something, then can I provide the question in the first lines by creating a comment I mean can we solve questions other than algorithms and known stuff.
