### ISSUE TITLE
Python Programs

### ISSUE THREAD

**Issue by sujata13** [sujata13/HacktoberFest-2020#7]
Write Python Programs in language specific folder. <br/>
File Name format- [Your UserName]_filename
 <br/>
Don't forget to star the repository and follow the author.
<br/>
<b>IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING<b>

**Comment by tanseersaji** [comment]
I'm Implementing LinkedList in Python

**Comment by sujata13** [comment]
Ok. Happy Coding!

**Comment by chrismilson** [comment]
I'll implement edit distance in python, where edit distance is the minimum number of character changes (add, remove, replace) to edit one string into another.

**Comment by shradhaagarwal01** [comment]
Hey, I am implementing sum of all nodes of a Binary Tree.

**Comment by sujata13** [comment]
Ok Happy Coding Everyone!!!

**Comment by arm210402** [comment]
i have created strong pass generator code using python

**Comment by sujata13** [comment]
Great!!!

**Comment by dj107** [comment]
Hey i'm implementing selection sort algorithm

**Comment by Amitsharma45** [comment]
hey i'm implementing stack and queue.

**Comment by giangngt** [comment]
I'm creating an email checker (in the format of string + @ + string + . + string)

**Comment by SeaSkyThe** [comment]
Implementing Merge Sort

**Comment by sk1122** [comment]
I will make login system using Python

**Comment by python1neo** [comment]
making a Simple Dice game>>

**Comment by komnen0v1c** [comment]
I will submit sudoku solver

**Comment by gaurangkeluskar22** [comment]
I would like to add Bubble Sort algorithm.
